logging:
  level:
    root: info
  file:
    name: springData.log
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/warehouse
    username: postgres
    password: erth
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:auto: validate
